### ISSUE TITLE
local variable 'status' referenced before assignment

### ISSUE THREAD

**Issue by ilvalle** [niphlod/cs_monitor_plugin#2]
Hi, I think you have to replace status with 'status' in line plugin_cs_monitor.py:382

``` python
Traceback (most recent call last):
  File "/home/pvalleri/src/web2py/gluon/restricted.py", line 212, in restricted
    exec ccode in environment
  File "/home/pvalleri/src/web2py/applications/scapp/controllers/plugin_cs_monitor.py", line 604, in <module>
  File "/home/pvalleri/src/web2py/gluon/globals.py", line 194, in <lambda>
    self._caller = lambda f: f()
  File "/home/pvalleri/src/web2py/gluon/tools.py", line 2971, in f
    return action(*a, **b)
  File "/home/pvalleri/src/web2py/applications/scapp/controllers/plugin_cs_monitor.py", line 557, in analyze_task
    gb_when_rows, jgb_when_series = bydate(q, mode)
  File "/home/pvalleri/src/web2py/applications/scapp/controllers/plugin_cs_monitor.py", line 382, in bydate
    if status not in gb_when_series:
UnboundLocalError: local variable 'status' referenced before assignment
```

**Comment by niphlod** [comment]
not quite, but thanks for reporting it...
